version: '3.8'

services:
  backend:
    build:
      context: ./Back
    ports:
      - "8080:8080"  
    environment:
      VITE_EMAIL_INDEXER_USER: admin
      VITE_EMAIL_INDEXER_PASSWORD: Complexpass#123

  frontend:
    build:
      context: ./Visualizer
    ports:
      - "80:5173" 
