export const PAGINATION_VALUE = 21;
export const MATCH_PHRASE = "matchphrase";
export const MATCH_ALL = "matchall";
export const METHOD_GET = "GET";
export const SERVER = "http://localhost:8080";
export const ENDPOINT = "/search";
export const AUTHORIZATION_LEVEL = "Basic ";
export const USER = import.meta.env.VITE_EMAIL_INDEXER_USER;
export const PASSWORD = import.meta.env.VITE_EMAIL_INDEXER_PASSWORD;
