export const PAGINATION_VALUE = 20;
export const MATCH_PHRASE = "matchphrase";
export const MATCH_ALL = "matchall";
export const METHOD_GET = "GET";
export const SERVER = "http://localhost:8080";
export const GET_SEARCHED_MAILS_ENDPOINT = "/search";
export const GET_SINGLE_MAIL_ENDPOINT = "/single"
export const AUTHORIZATION_LEVEL = "Basic ";
export const USER = import.meta.env.VITE_EMAIL_INDEXER_USER;
export const PASSWORD = import.meta.env.VITE_EMAIL_INDEXER_PASSWORD;
